# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      version:
        description: "Version tag (e.g., v1.2.3)"
        required: true
        default: "v0.0.0"
        type: string

env:
  REGISTRY: docker.io
  IMAGE_NAME: golemnetwork/altda-deployer

jobs:
  release:
    name: Create Release
    runs-on: cluster-runner
    permissions:
      contents: write # Required for creating releases and tags
      packages: write # Required for publishing Docker images
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      # Necessary for installing nix (alternative: create a custom gh runner image)
      - name: Install xz
        run: |
          sudo apt-get update
          sudo apt-get install -y xz-utils

      - name: Install nix
        uses: cachix/install-nix-action@7be5dee1421f63d07e71ce6e0a9f8a4b07c2a487 # v31.6.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create tag if workflow_dispatch
        if: github.event_name == 'workflow_dispatch'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag -a ${{ github.event.inputs.version }} -m "Release ${{ github.event.inputs.version }}"

      - name: Run GoReleaser
        run: nix develop .#ci --command goreleaser release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
